version: "3.9"
services:
  lighthouse-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lighthouse-dashboard
    entrypoint: /bin/bash
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html/app
    tty: true